### PR TITLE
Add a nanoc filter for erubi

### PR DESCRIPTION
**Pull request by Fjan**
Add a nanoc filter for Erubi

### To do
The test runs but Rubocop flags the use of ```eval```. Erb / Erubis / Erubi all need to use eval, and can never be run on untrusted input, so I would suggest suppressing the warning.

### Related issues
https://github.com/nanoc/features/issues/8
https://github.com/nanoc/nanoc/issues/1096

### CODE REVIEW

**Comment by ddfreyne** [comment]
Update `.rubocop` to exclude the the `Security/Eval` check for this file:

```
Security/Eval:
  Exclude:
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/nanoc/base/entities/code_snippet.rb'
    - 'lib/nanoc/filters/erubi.rb'
```

**Comment by ddfreyne** [comment]
Looks good! I’ll release this as part of Nanoc 4.7.

**Comment by ddfreyne** [comment]
@Fjan I forgot to attribute you in the release notes for 4.7, but it’ll be rectified in the 4.7.1 release notes (see e753887880bea7be92fab871c5c6f41e21f322d6). Sorry!

**Comment by Fjan** [comment]
Sure, no problem :-)

**Pull request merged**
