### PR TITLE
Allow turning on line numbers for the Rouge formatter

### PR DESCRIPTION
**Pull request by whitequark**
... similarly to what CodeRay allows.

### CODE REVIEW

**Comment by ddfreyne** [comment]
Looks interesting. Do you think it makes more sense to allow passing a custom formatter instance (`formatter: Rouge::Formatters::Whatever.new(…)`)?

FYI: If you rebase on top of `master`, the build failures will go away.

**Comment by whitequark** [comment]
I think it's convenient to not have to care about Rouge's API for anyone using nanoc for basic tasks.

**Comment by whitequark** [comment]
Rebased.

**Comment by barraq** [comment]
@whitequark this is connected to https://github.com/nanoc/nanoc/pull/880 did you try out?

**Comment by whitequark** [comment]
@barraq I've missed that PR. I've looked at it and yeah, that should work for me as well.

**Comment by ddfreyne** [comment]
I think my preference goes out for #880 rather than this PR, as it’s more generic and solves the same problem.

**Comment by whitequark** [comment]
Well... this PR is done and #880 is not. But alright.

**Pull request closed without merging**
