### PR TITLE
Make globs and indentifiers with extensions the default

### PR DESCRIPTION
**Pull request by ddfreyne**
* [x] Make globs the default
* [x] Make identifiers with extensions the default

I don’t like the option names for enabling/disabling these (`pattern_syntax: glob/null` and `identifier_style: full/stripped`).

### CODE REVIEW

**Comment by bobthecow** [comment]
stripped is weird. null is weird. glob isn't the best, but at least it's accurate.

**Comment by ddfreyne** [comment]
More ideas for identifiers:

* `identifier_type: with_ext`
* `identifier_type: without_ext`

And for patterns:

* `pattern_type: glob`
* `pattern_type: legacy_wildcard`
* `pattern_type: legacy`

(I prefer `_type` more than syntax/style.)

**Comment by bobthecow** [comment]
I'm leaning toward:

 * `identifier_type: full`
 * `identifier_type: legacy`

and

 * `pattern_type: glob`
 * `pattern_type: legacy`

Let's make it very clear why the second option for each exists.

**Comment by gpakosz** [comment]
I'm with @bobthecow

**Comment by ddfreyne** [comment]
I’ll follow up with a second PR that changes the names to what @bobthecow suggests.

**Comment by ddfreyne** [comment]
See #593.

**Pull request merged**
