### PR TITLE
Rename nanoc to Nanoc

### PR DESCRIPTION
**Pull request by ddfreyne**
Fix for #596.

The product name becomes _Nanoc_ (used to be _nanoc_). The following items are not affected:

* The command-line tool
* The library name
* The gem name

### CODE REVIEW

**Comment by bobthecow** [comment]
:+1:

**Comment by opensourcegrrrl** [comment]
+1

**Comment by gpakosz** [comment]
I really don't understand the motivation behind this.

**Comment by ddfreyne** [comment]
@gpakosz In English, proper nouns are capitalised. I called this project “nanoc”, which deviates from tis rule. It causes needless confusion, and most people already call it “Nanoc”.

Additionally, names that start with a lowercase letter are capitalised when they appear at the beginning of a sentence. This make sense as starting a sentence with a lowercase letter makes it harder to distinguish between sentences.

All in all, picking _Nanoc_ as the project name makes life easier for everyone.

**Comment by gpakosz** [comment]
Fine.

`bundle exec Nanoc compile`, I don't see the point.

**Comment by ddfreyne** [comment]
The executable would still be called _nanoc_ (not _Nanoc_).

**Comment by bobthecow** [comment]
> The product name becomes Nanoc (used to be nanoc). The following items are not affected:
>
> * The command-line tool
> * The library name
> * The gem name

**Comment by gpakosz** [comment]
Ah my bad I overlooked the **not affected** part. I thought it would be affected :) Same for the gem name.

**Comment by ddfreyne** [comment]
The web site will be updated in a separate PR.

**Pull request merged**
