### PR TITLE
Add behaviors to #content_for

### LINKED ISSUE #704: Multiple "content_for" calls should concatenate
Currently, when you call `content_for` twice on a page the second call will overwrite the content captured for the first one. It would be more useful if they concatenated, just like the behaviour of content_for in Rails. Consider this example that would be made possible:
```
<% content_for :head do %>
   <link ref="...">
<% end %>
```
And somewhere else you could do:
```
<% content_for :head do %>
   <script src="...">
<% end %>
```
And then put a single `<%= content_for :head %>` in the layout.

It would actually be a very simple change in nanoc/helpers/capturing.rb. Just replace line 45 with this:
```
if @store[item.identifier][name] then
  @store[item.identifier][name] << content
else 
  @store[item.identifier][name] = content
end
```

### PR DESCRIPTION
**Pull request by ddfreyne**
Fixes #704.

`#content_for`, when given a block, now gains a second parameter, `:existing`, which determines what to do when existing content already exists. The three possible values are:

* `:error` (current behavior): when content already exists and is not identical, raise an error.
* `:overwrite`: overwrite the previously captured content with the newly captured content
* `:append`: append the newly captured content to the previously captured content

For example:

```rhtml
<% content_for(:stuff) do %>banana<% end %>
<% content_for(:stuff, existing: :append) do %>donkey<% end %>
```

will result in `content_for(:stuff)` containing `"bananadonkey"`

```rhtml
<% content_for(:stuff) do %>banana<% end %>
<% content_for(:stuff, existing: :error) do %>donkey<% end %>
```

will raise an exception

```rhtml
<% content_for(:stuff) do %>banana<% end %>
<% content_for(:stuff, existing: :overwrite) do %>donkey<% end %>
```

will result in `content_for(:stuff)` containing `"donkey"`

### CODE REVIEW

**Comment by ddfreyne** [comment]
CC @Fjan — this  is the behavior you’re looking for.

**Comment by Fjan** [comment]
Yes, thank you. I would probably still be a good idea to make :append the default at some point to make it's behaviour similar to the content_for in Rails.

**Comment by ddfreyne** [comment]
That’ll have to be for Nanoc 5 (since it’s a breaking change).

**Comment by Fjan** [comment]
We can be pretty confident that the current default behaviour is not used by anyone, because it would raise an exception, so I wouldn't call it a breaking change. But I'm fine with waiting until the next version.

**Pull request merged**
