### PR TITLE
Add release notes for 3.7.5

### PR DESCRIPTION
**Pull request by ddfreyne**
Work in progress, since we’re not ready for 3.7.5 yet!

### CODE REVIEW

**Comment by ddfreyne** [comment]
This PR now contains everything for 3.7.5.

@nanoc/contributors does this look good?

**Comment by mpapis** [comment]
looks good, are we waiting on #480 ?

**Comment by ddfreyne** [comment]
#480 can go in a future release too.

**Comment by DaveEveritt** [comment]
Nice consolidation - looks good to me concerning the issues I've followed (dotfiles, Ruby 1.8.* drop support).

**Comment by ddfreyne** [comment]
I plan on releasing 3.7.5 tomorrow morning.

(Whether this actually works out depends on how early I get up and how much time I waste browsing cute pictures on the internet.)

**Comment by ddfreyne** [comment]
Fixed one typo (missing `)`).

**Pull request merged**
