### PR TITLE
Run less filter on main fiber

### PR DESCRIPTION
**Pull request by ddfreyne**
This ensures that `Less` is always invoked on the main fiber. Potential fix/workaround for #999.

* Added `Filter#on_main_fiber`, which executes the given block on the main fiber. This is the main mechanism that makes the Less filter work again.

* Converted all Less tests to specs. These are high-level tests (compiling using the CLI) because the Less filter is somewhat annoying to test otherwise (it now requires interaction with the compiler).

* Two new Less specs that did not exist before are skipped for now, as I can’t get them to work. Will investigate in another PR.

### CODE REVIEW

**Comment by ddfreyne** [comment]
`less_spec.rb` now passes, but `test_less.rb` fails, with two distinct reasons:

* `Less::Error: Maximum call stack size exceeded`
* `FiberError: dead fiber called`

**Comment by ddfreyne** [comment]
False hope: `less_spec.rb` fails too, sometimes.

**Comment by ddfreyne** [comment]
Not quite working. I reported an issue to `therubyracer`: cowboyd/therubyracer#421.

**Comment by ddfreyne** [comment]
Added a mechanism to make code execute on the main fiber, and made the less filter use it. This seems to work!

**Comment by ddfreyne** [comment]
CC @RubenVerborgh — can you verify that this PR fixes your problem (#999)?

**Comment by ddfreyne** [comment]
Will merge because I cannot reproduce the problem on Travis CI nor locally on a Debian VM.

**Comment by RubenVerborgh** [comment]
That was fast 😉  I'll test later today.

**Comment by ddfreyne** [comment]
The two new skipped Less specs are implemented in #1003.

**Comment by RubenVerborgh** [comment]
Looks good to me.

**Pull request merged**
