### PR TITLE
Improve erubi filter error output

### PR DESCRIPTION
**Pull request by Fjan**
this fixes https://github.com/nanoc/nanoc/issues/1255

### CODE REVIEW

**Comment by ddfreyne** [comment]
Looks good! Can you add a test for this, though? You can use this as a base: https://github.com/nanoc/nanoc/blob/master/test/filters/test_erubi.rb#L24-L37

**Comment by Fjan** [comment]
Ok, I added a test for the specific case I mentioned in the bug report but the test does not create a file on disk so the improvement that the improved error message will show a file name is not really clearly visible

**Comment by ddfreyne** [comment]
Please create a new test, rather than extending the existing one.

For the sake of testing this: you can check whether the exception stack trace contains the item name. That should do it!

**Comment by Fjan** [comment]
I had no luck making an item name appear in the test. Sorry, I really don't have more time to work on this any time soon. As an aside, none of the other filters check for the presence of the item name being present in the error message, so testing this seems more trouble than it's worth for such a small embellishment.

**Comment by ddfreyne** [comment]
All bug fixes need an accompanying test. I’ll work on a fix for this.

**Comment by ddfreyne** [comment]
Replaced by #1259.

**Pull request closed without merging**
