### PR TITLE
Configurable meta extension

### PR DESCRIPTION
**Pull request by vsuhachev**
Possibility to redefine metadata file extension for "filesystem" datastore

### Detailed description

added datastore configuratuon param `meta_ext`

### To do

* [ ] Tests
* [ ] Documentation
* [ ] Feature flags

### Related issues

None

### CODE REVIEW

**Comment by ddfreyne** [comment]
Could you elaborate on the use case for making `meta_ext` customisable?

I’d like to limit the number of configuration options in Nanoc to a minimum, and so I’m hesitant to approve this change unless it solves a real problem.

**Comment by gpakosz** [comment]
I second @ddfreyne, beside `.yaml`, or `.yml` what the extension could be?

Maybe nanoc should support these both and that's it.

**Comment by vsuhachev** [comment]
If Filesystem is a private API then this improvement loses his reasons. It looks like I'll have to write my DataSource from scratch

**Comment by ddfreyne** [comment]
@vsuhachev Is there a reason why using `yaml` is not possible for you?

**Comment by ddfreyne** [comment]
FWIW, the [YAML FAQ](http://www.yaml.org/faq.html) indicates `.yaml` as the preferred extension:

> *Is there an official extension for YAML files?*
>
> Please use ".yaml" when possible.

**Pull request closed without merging**
