### PR TITLE
Added `.atom` to default text extensions

### PR DESCRIPTION
**Pull request by yannickihmels**

### CODE REVIEW

**Comment by gpakosz** [comment]
What is this file extension suppose to refer to?

**Comment by yannickihmels** [comment]
It refers to atom feeds (MIME type is application/atom+xml).

**Comment by gpakosz** [comment]
And you have Atom feeds stored in `.atom` files inside your `content/` directory?

**Comment by yannickihmels** [comment]
Yes, because it’s the extension for atom feed files. Using `.atom` as extension allows me to set the proper MIME type in `.htaccess` file.

**Comment by gpakosz** [comment]
Hmm yes but, likely Nanoc generates e.g. `output/feed.atom` from e.g. `content/feed.erb`. In `content/feed.erb` you typically list items and format them into an Atom feed.

In that respect, there's no reason to change the content of the `text_extensions` array.

**Comment by yannickihmels** [comment]
Then why there is `html`, `htm` or `xhtml` in the `text_extensions` array? Nanoc would route `content/hello-world.erb` to `output/hello-world.html` if you instruct it in the `Rules` file.

**Comment by ddfreyne** [comment]
:+1:

**Comment by ddfreyne** [comment]
FYI, this will land in nanoc 4.1, since nanoc 4.0 is feature-frozen.

**Pull request merged**
