### PR TITLE
Add AsciiDoc files to text_extensions

### PR DESCRIPTION
**Pull request by suy**

### CODE REVIEW

**Comment by suy** [comment]
I've sent the request to master because the layout has changed, and is not a "critical" thing. Users will just add the file names to their YAML.

**Comment by ddfreyne** [comment]
Awesome, thanks!

**Comment by gpakosz** [comment]
Not so awesome? http://www.methods.co.nz/asciidoc/faq.html#_what_is_the_preferred_file_name_extension_for_asciidoc_files

**Comment by ddfreyne** [comment]
@gpakosz Realistically, people use `.adoc` or `.asciidoc` so that text editors recognise and highlight it properly. GitHub also uses those two extensions.

**Comment by ddfreyne** [comment]
FYI: http://asciidoctor.org/docs/asciidoc-recommended-practices/#document-extension

**Comment by suy** [comment]
Yep, that was exactly my reasoning: On Github or Gitlab this is recognized, and the ".asc" I tend to see it as the "ascii armored GPG something".

**Pull request merged**
